### ISSUE TITLE
page margins

### ISSUE THREAD

**Issue by owise1** [demand-progress/biden-cabinet-www#26]
hey @csummer I need your help on this one.  Eleanor likes the margins on the ".page" pages, but not the homepage. Could you make the homepage margins look like the other pages?  Also, we need to wrap the site like we did with the other one so the main content never gets wider than say 1200px.

**Comment by csummer** [comment]
sure thing, I'll do that now

**Comment by csummer** [comment]
@owise1 - just made a commit with some quick adjustments. Is there anything else that should be nudged over? probably e.g. the main nav links and the logo?

And I set the max page width to 1400, I guess because my tiny old laptop is 1300-something px wide, and there start to be tough questions to answer once you hit the max. Like the background sticking out around the page content. Ideally we would probably want to extend all background colors to the width of the page? I'll play around with that and see if I can find a solution.
